### ISSUE TITLE
Failed to link vertex and fragment shaders

### ISSUE THREAD

**Issue by HuiGeGeGitHub** [tensorflow/tfjs-wechat#11]
![image](https://user-images.githubusercontent.com/22650901/61202186-6e6a6c00-a719-11e9-8c61-01caf4f15a8c.png)
`if (this.mobilenetModel) {
            this.mobilenetModel.classify(frame.data, { width: frame.width, height: frame.height });
 }`  
Report an error "Failed to link vertex and fragment shaders" in mobilenet demo

**Comment by pyu10055** [comment]
@HuiGeGeGitHub is there an error generated from the dev tool or form the mobile device?
And please indicate all the versions (tfjs, plugin, wechat ide, wechat api). thanks.

**Comment by HuiGeGeGitHub** [comment]
This error occurred on the dev tool，On the  mobile device is normal. 
The versions ( tfjs v1.2.2 wechat ide v1.02.1907081).
Maybe the dev tool does not support GPU?

**Comment by pyu10055** [comment]
you are on windows right? maybe try the latest nightly build from here
https://developers.weixin.qq.com/miniprogram/dev/devtools/nightly.html

**Comment by HuiGeGeGitHub** [comment]
yes on windows , Still reporting this error? Thank you for your support🍗

**Comment by pyu10055** [comment]
@HuiGeGeGitHub This is a likely a wechat IDE issue, I have forwarded this error to WeChat team.

**Comment by HuiGeGeGitHub** [comment]
Thank you  @

**Comment by HuiGeGeGitHub** [comment]
@pyu10055  Thank you

**Comment by ele828** [comment]
Hi @HuiGeGeGitHub , this is Eric from WeChat. I suspect this is something to do with the GPU on your Windows PC, specifically, some shader operations are not supported by your GPU. 
You can check if the mobilenet model runs on your 
Chrome browser using tf.js GPU backend. If so, please provide us with more details about the graphics card and we can look further into it.

**Comment by HuiGeGeGitHub** [comment]
the mobilenet model  demo runs normally on my Chrome browser. But the Wechat dev tool is wrong.

**Comment by ele828** [comment]
@HuiGeGeGitHub Here is the same issue someone else had on MS Edge:
https://stackoverflow.com/questions/55188619/ms-edge-script5022-failed-to-link-vertex-and-fragment-shaders

Looks like adding `tf.ENV.set('WEBGL_PACK', false)` fixes the issue, although I am not sure what's going on under the hood. But can you try adding this to `onLaunch()` lifecycle in your `app.json` and see if it works?

**Comment by pyu10055** [comment]
cc @annxingyuan seem WEBGL_PACK does not work on MS edge browser.
