### ISSUE TITLE
有没有兼容movenet的代码示例，现在movenet没有办法用img.slice()方法做全屏的分割

### ISSUE THREAD

**Issue by WD-CHINA** [tensorflow/tfjs-wechat#113]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tomatoeggs** [comment]
```javascript
var frameObj = {
  data: new Uint8Array(frame.data),
  height: Number(frame.height),
  width: Number(frame.width)
};

const resized= this.padAndResizeTo(frameObj, [this.displaySize.height,this.displaySize.width]);
```


```javascript
padAndResizeTo(input, [targetH, targetW]) {
  const [height, width] = [input.height, input.width];
  const targetAspect = targetW / targetH;
  const aspect = width / height;
  let [padT, padB, padL, padR] = [0, 0, 0, 0];
   if (aspect > targetAspect) {
    // pads the width
    padT = 0;
    padB = 0;
    padL = Math.round(0.5 * (targetAspect * height - width));
    padR = Math.round(0.5 * (targetAspect * height - width));
  } else {
    // pads the height
     padT = Math.round(0.5 * ((1.0 / targetAspect) * width - height));
    padB = Math.round(0.5 * ((1.0 / targetAspect) * width - height));
    padL = 0;
    padR = 0;
  }
    
  const resized = tf.tidy(() => {
    let imageTensor = tf.browser.fromPixels(input);
    imageTensor = tf.pad3d(imageTensor, [[padT, padB], [padL, padR], [0, 0]]);
    let result = tf.image.resizeBilinear(imageTensor, [targetH, targetW]);
    imageTensor.dispose();
    return result;
  });
    
   return resized;
}
```

**Comment by WD-CHINA** [comment]
> ```js
> var frameObj = {
>   data: new Uint8Array(frame.data),
>   height: Number(frame.height),
>   width: Number(frame.width)
> };
> 
> const resized= this.padAndResizeTo(frameObj, [this.displaySize.height,this.displaySize.width]);
> ```
> 
> ```js
> padAndResizeTo(input, [targetH, targetW]) {
>   const [height, width] = [input.height, input.width];
>   const targetAspect = targetW / targetH;
>   const aspect = width / height;
>   let [padT, padB, padL, padR] = [0, 0, 0, 0];
>    if (aspect > targetAspect) {
>     // pads the width
>     padT = 0;
>     padB = 0;
>     padL = Math.round(0.5 * (targetAspect * height - width));
>     padR = Math.round(0.5 * (targetAspect * height - width));
>   } else {
>     // pads the height
>      padT = Math.round(0.5 * ((1.0 / targetAspect) * width - height));
>     padB = Math.round(0.5 * ((1.0 / targetAspect) * width - height));
>     padL = 0;
>     padR = 0;
>   }
>     
>   const resized = tf.tidy(() => {
>     let imageTensor = tf.browser.fromPixels(input);
>     imageTensor = tf.pad3d(imageTensor, [[padT, padB], [padL, padR], [0, 0]]);
>     let result = tf.image.resizeBilinear(imageTensor, [targetH, targetW]);
>     imageTensor.dispose();
>     return result;
>   });
>     
>    return resized;
> }
> ```

谢谢，已经自己写方法处理好了，跟你的方法差不太多
