### ISSUE TITLE
Can you add an example of the ssd_mobilenet model?

### ISSUE THREAD

**Issue by yichuxue** [tensorflow/tfjs-wechat#14]
**Is your feature request related to a problem? Please describe.**
Can you add an example of the ssd_mobilenet model?

**Describe the solution you'd like**
Load the ssd_mobilenet model. Make predictions, get scores and bboxes and tags.

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by pyu10055** [comment]
Ok will look into that
