### ISSUE TITLE
tfl.loadLayersModule cannot load weight file from server

### ISSUE THREAD

**Issue by jl-sun** [tensorflow/tfjs-wechat#21]
TensorFlow.js version: 1.2.6
tfjs-wechat plugin version: 0.0.5
WeChat version: 7.0.5
WeChat base API version: 2.8.0
WeChat IDE version: v1.02.1908012 (Nightly)

When I try to load the model on Android or iOS devices (Huawei P10plus, iPhoneXR, Samsung Note8, MI 9SE), model.json can be loaded while the request for group1-shard1of1.bin is always pending. model.json and group1-shard1of1.bin are in the same directory and both of them are accessible. 

Screenshot:
![image](https://user-images.githubusercontent.com/30384939/62546941-fe25b500-b896-11e9-991f-54298ea77f5f.png)
![image](https://user-images.githubusercontent.com/30384939/62547098-3e853300-b897-11e9-885a-84a37dbba953.png)

**Comment by pyu10055** [comment]
@jl-sun your screenshot looks like inside the IDE, and your request content-type is wrong.
The model loading works on my IDE which is the stable version 1.02.1907160 and on my phones.
But I think the main difference is I don't have base API version 2.8.0 available, I am using 2.7.7.
Can you try to use 2.7.7 to isolate the problem. thanks!

**Comment by jl-sun** [comment]
@pyu10055 Thanks for your reply! Using 2.7.7 (Samsung Note8, Android 9), the problem still exists. Here's what I've got:
![image](https://user-images.githubusercontent.com/30384939/62561851-9da47100-b8b2-11e9-9122-097d49e90624.png)
Also, it seems that the wrong request content-type in the IDE doesn't affect the loading process:
![image](https://user-images.githubusercontent.com/30384939/62562225-54085600-b8b3-11e9-9e44-8e442a37efe3.png)
![image](https://user-images.githubusercontent.com/30384939/62562292-68e4e980-b8b3-11e9-91be-56f1df9bf8e4.png)

**Comment by jl-sun** [comment]
@pyu10055 Could you please give me some guidance on how to correct the request content-type? I tried to look through model.json and models.ts but I don't know which lines to modify.

**Comment by pyu10055** [comment]
@jl-sun you should take a look at the miniprogram_npm/fetch_wechat/index.js file, line 62.

in the fetchFunc() method, it set the request data type based on the file extension.
It should be 'arraybuffer' for the weight files. can you print out what dataType it is setting on those
failing phones? thanks!

**Comment by jl-sun** [comment]
@pyu10055 Here's the log:
![image](https://user-images.githubusercontent.com/30384939/62580397-ab6ced00-b8d8-11e9-98bf-04f251ee270a.png)

**Comment by pyu10055** [comment]
Is this log from the phone? this looks correct. does this problem only exist on the two phones you mentioned? Maybe the wechat wx.request API is not generating the correct header.

can you try to load the file directly in your mini app directly using the wx.request API

```
wx.request({
  url: 'your_weight_file_url',
  method: 'GET',
  dataType: 'arraybuffer',
  responseType: 'arraybuffer',
  header: {
    'content-type': 'application/octet-stream' 
  },
  success (res) {
    console.log(res.data)
  }
})
```

**Comment by jl-sun** [comment]
@pyu10055 Yes, the log is from the failing phones. I've tested on the four phones and the same problem exists on all of them. Unfortunately, the request is always pending even if I directly use wx.request to load the file:
![image](https://user-images.githubusercontent.com/30384939/62583660-b1b49680-b8e3-11e9-877e-daa2171dde75.png)

**Comment by pyu10055** [comment]
@jl-sun I tried your model link, it does generate a script error on the phone. This could be a server setting issue, maybe try to host the files on a different host? 
some time having an extension on the filename also helps.
you can try to change the weight file name to group1-shard1of1.bin
and manually edit the model.json file accordingly.

**Comment by jl-sun** [comment]
@pyu10055 Thanks for your advice. I tried the model link provided in the demo (mobilenet) and the pending issue still exists (though the link is accessible in my browser).
![image](https://user-images.githubusercontent.com/30384939/62602632-bb132280-b926-11e9-8808-30b8b8034134.png)
![image](https://user-images.githubusercontent.com/30384939/62602452-5bb51280-b926-11e9-924f-c7946ceaed75.png)
After changing the request content-type, the files are still not loaded:
![image](https://user-images.githubusercontent.com/30384939/62602615-b3ec1480-b926-11e9-94cd-7659dc3e412a.png)

**Comment by jl-sun** [comment]
@pyu10055 I tried the methods you mentioned above but the outcomes are the same. Any other approaches to solve the problem?

**Comment by pyu10055** [comment]
@jl-sun is this related to the request domain whitelist in wechat admin page?

**Comment by jl-sun** [comment]
@pyu10055 No, the request domain has already been added to the whitelist.

**Comment by jl-sun** [comment]
@pyu10055 The problem has been solved. It turns out to be related to the remote debug mode in the Wechat IDE. (the reason remains unknown, check "Does not verify valid domain names" option does not help) In the experience version of the mini app, the file is successfully loaded.

**Comment by jl-sun** [comment]
@pyu10055 Thanks a lot for taking the time to help me out!
