### ISSUE TITLE
How can I know the classes label in the mobilenet demo?

### ISSUE THREAD

**Issue by allrightzhu** [tensorflow/tfjs-wechat#23]
In the mobilenet demo,the result just show the score and prediction time,but whitch classes it predicted?

**Comment by pyu10055** [comment]
The result also contains the class id, you can look up the class name using this code:

https://github.com/tensorflow/tfjs-models/blob/master/mobilenet/src/imagenet_classes.ts

**Comment by allrightzhu** [comment]
Maybe I got a wrong result,It didn't match the imagenet_classes. Thank you!

**Comment by allrightzhu** [comment]
> The result also contains the class id, you can look up the class name using this code:
> 
> https://github.com/tensorflow/tfjs-models/blob/master/mobilenet/src/imagenet_classes.ts

Why the length of tensor.argMax().dataSync() is 1001, the length of classes in imagenet_classes.ts  is 
 1000?
