### ISSUE TITLE
error TS2688：Cannot find type definition file for ‘jasmine’

### ISSUE THREAD

**Issue by Inchel214** [tensorflow/tfjs-wechat#26]
运行npm run build时候报错

**Comment by pyu10055** [comment]
@Inchel214 please follow the issue template to provide more details on what version of libraries you are using.

If you want to run the demo code, please follow the README [here](https://github.com/tensorflow/tfjs-wechat/blob/master/demo/mobilenet/README.md)

**Comment by exist2disappear** [comment]
i follow this [README](https://github.com/tensorflow/tfjs-wechat/blob/master/demo/mobilenet/README.md),I have same problem. 

my log here :
> tsc

error TS2688: Cannot find type definition file for 'jasmine'.


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! tfjs-wechat-plugin-mobile-example@0.0.1 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the tfjs-wechat-plugin-mobile-example@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by shuxiongwuziqi** [comment]
Same for me. How to solve this problem?

**Comment by exist2disappear** [comment]
> Same for me. How to solve this problem?

谷歌大佬估计不管这个分支了，我直接把这个依赖删除了，删了主体功能可以用的

**Comment by shuxiongwuziqi** [comment]
我直接看着typescript源码，自己写成js代码，也可以成功运行。



---Original---
From: "yuqing ***@***.***&gt;
Date: Tue, Jul 6, 2021 10:46 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tensorflow/tfjs-wechat] error TS2688：Cannot find type definition file for ‘jasmine’ (#26)




  
Same for me. How to solve this problem?
  
谷歌大佬估计不管这个分支了，我直接把这个依赖删除了，删了主体功能可以用的

**Comment by 223yang** [comment]
> 我直接看着typescript源码，自己写成js代码，也可以成功运行。
> […](#)
> ---Original--- From: "yuqing ***@***.***&gt; Date: Tue, Jul 6, 2021 10:46 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [tensorflow/tfjs-wechat] error TS2688：Cannot find type definition file for ‘jasmine’ (#26) Same for me. How to solve this problem? 谷歌大佬估计不管这个分支了，我直接把这个依赖删除了，删了主体功能可以用的 — You are recg this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
我也遇到了相同的问题，请问方便把你的代码借我学习一下吗？（邮箱1099179688@qq.com）（毕业设计所需，非商业用途

**Comment by 223yang** [comment]
> 

我也遇到了相同的问题，请问方便把你的代码借我学习一下吗？（毕业设计所需，非商业用途

**Comment by 223yang** [comment]
> > Same for me. How to solve this problem?
> 
> 谷歌大佬估计不管这个分支了，我直接把这个依赖删除了，删了主体功能可以用的

我也遇到了相同的问题，请问方便把你的代码借我学习一下吗？邮箱1099179688@qq.com（毕业设计所需，非商业用途

**Comment by exist2disappear** [comment]
> > > Same for me. How to solve this problem?
> > 
> > 
> > 谷歌大佬估计不管这个分支了，我直接把这个依赖删除了，删了主体功能可以用的
> 
> 我也遇到了相同的问题，请问方便把你的代码借我学习一下吗？邮箱[1099179688@qq.com](mailto:1099179688@qq.com)（毕业设计所需，非商业用途

好久没看，这段练习代码弄丢了，同学自己删除依赖试试吧
