### ISSUE TITLE
appServiceSDKScriptError Fail to compile fragment shader;

### ISSUE THREAD

**Issue by NalvyBoo** [tensorflow/tfjs-wechat#40]
On Android devices , run `./demo/mobilenet`：

```
appServiceSDKScriptError Fail to compile fragment shader;
at api onCameraFrame callback function
Error: Fail to compile fragment shader.
```

![log](https://user-images.githubusercontent.com/19989328/70303091-a9d91480-1839-11ea-80b3-f107e9ad2794.png)

TensorFlow.js version 1.2.7
tfjs-wechat plugin version 0.0.6
WeChat version 7.0.9
WeChat base API version 2.9.4
WeChat IDE version 1.02.1911181

**Comment by NalvyBoo** [comment]
Additional information
Phone model：红米手机 Redmi3
Android version : 5.1.1

**Comment by pyu10055** [comment]
@NalvyBoo can you first try to upgrade to the latest version of tfjs (1.4.0)
Is this error currently happening in the IDE or just on this particular phone?

Are there detail logs on the what fragment shader is failing (it usually prints out the neighbor lines)? Thanks

**Comment by NalvyBoo** [comment]
> @NalvyBoo can you first try to upgrade to the latest version of tfjs (1.4.0)
> Is this error currently happening in the IDE or just on this particular phone?
> 
> Are there detail logs on what fragment shader is failing (it usually prints out the neighbor lines)? Thanks

Thank you for your reply.

1.  I upgraded the version to 1.4.0 and the error persists.
2. This error does not appear in the IDE and iPhone, but only on Android phones.
3. I tried using `try catch` to find the error on this line (path:` ./demo/mobilenet/model/classifier.ts` ):
```typescript
const pixels = temp.slice([0, 0, 0], [-1, -1, 3]).resizeBilinear([224, 224]);
```

and error is:
```error
<Error: Failed to compile fragment shader.>
```

**Comment by pyu10055** [comment]
@NalvyBoo sorry for not responding to this issue, we don't have the phone to test against. Wondering if you have made any progress on this? If not, please try the latest releases again. thanks.

**Comment by pyu10055** [comment]
closing this issue due to lack of activities, will reopen if needed.
