### ISSUE TITLE
new wechat version7.0.10 android,probability is 0 for any mobilenet model's class

### ISSUE THREAD

**Issue by allrightzhu** [tensorflow/tfjs-wechat#41]
After today I got an new version(7.0.10) wechat,all my andorid devices got an probability result:0,maybe there is some bug with the new version wechat.

**Comment by GaussRieman** [comment]
I've got the same problem!

**Comment by iooops** [comment]
I'm unable to load graph model. It was initially working on any Android devices without version update.

**Comment by HunterXuan** [comment]
It seems that wechat made some changes to the api `wx.createOffscreenCanvas()`.
And here are my two temporary solutions that my help: https://github.com/HunterXuan/wx-tfjs-demo/issues/19
