### ISSUE TITLE
new android wechat version 7.0.10 load cocossd model error

### ISSUE THREAD

**Issue by aohan237** [tensorflow/tfjs-wechat#43]
as the title said, on android wechat7.0.10, load cocossd model error, shows tensorshape is zero error

any older version of android wechat works fine

**Comment by iooops** [comment]
Same here. On Android Wechat 7.0.10, posenet model detections always have 0 score. Please solve this issue as soon as possible.

**Comment by aohan237** [comment]
@iooops 

it seems to be the wx.createOffscreenCanvas() problem
create a canvas by hand will be solve. 

> https://github.com/HunterXuan/wx-tfjs-demo/issues/19
```
    <camera frame-size="medium" bindinitdone="cameraInit" binderror="cameraError">
        <cax id="stage"></cax>
        <canvas type="webgl" id="myCanvas" hidden="{{ true }}"></canvas>
    </camera>
```

this solution will be fine. just add a webgl canvas on camera by hand .

--------------------------------------------------
it seems that android wechat 7.0.10 is a milestone update . it updates things on webgl and tests do not cover too much about it
so be careful with android wechat 7.0.10

**Comment by iooops** [comment]
How did you configure it in plugin.configPlugin?

**Comment by aohan237** [comment]
```
            if (!hasConfigPlugin) {
                plugin.configPlugin({
                    fetchFunc: fetchWechat.fetchFunc(),
                    tf,
                    canvas: wx.createOffscreenCanvas()
                }, false);
                //hasConfigPlugin = true;
            }
```

**Comment by iooops** [comment]
What about the created webgl canvas?

**Comment by aohan237** [comment]
@iooops  the first answer...

**Comment by iooops** [comment]
Do you have sample repo?

**Comment by aohan237** [comment]
sorry ,no

**Comment by iooops** [comment]
Ok I figured it out. Here's my solution.
`    var res = wx.getSystemInfoSync()
    let iOS = res.system.startsWith('iOS')
    const query = wx.createSelectorQuery()
    query.select('#myCanvas').node().exec((res) => {
      const canvas = res[0].node
      const gl = canvas.getContext('webgl')
      console.log('!!',canvas)
      plugin.configPlugin({
        // polyfill fetch function
        fetchFunc: fetchWechat.fetchFunc(),
        // inject tfjs runtime
        tf,
        // provide webgl canvas
        canvas: iOS ? wx.createOffscreenCanvas() : canvas,
        backendName: 'wechat-webgl-' + Math.random()
      });
      this.init()
    })`

**Comment by pyu10055** [comment]
@aohan237 thanks, WeChat engineers are looking into the problem, will update here if it is fixed.

**Comment by aohan237** [comment]
@pyu10055  thanks for updating information,too

**Comment by pyu10055** [comment]
@aohan237 Updates from WeChat, this will be fixed in the upcoming wechat common lib version 2.10.1 (hopeful released by tomorrow). Please try it out, and let us know if this issue is fixed. thanks.

**Comment by allrightzhu** [comment]
> @aohan237 Updates from WeChat, this will be fixed in the upcoming wechat common lib version 2.10.1 (hopeful released by tomorrow). Please try it out, and let us know if this issue is fixed. thanks.

Wechat common lib version 2.10.1 didn't fix this problem

**Comment by embbnux** [comment]
Same here in iOS 13.3.1 with wechat 7.0.10. I guess it is a webgl issue in 13.3.1 as https://github.com/tensorflow/tfjs-wechat/issues/10

**Comment by pyu10055** [comment]
@allrightzhu any luck with the latest wechat version 2.10.3? thanks

**Comment by allrightzhu** [comment]
> @allrightzhu any luck with the latest wechat version 2.10.3? thanks

It's ok on new version.

**Comment by pyu10055** [comment]
thanks for confirming.
