### ISSUE TITLE
save models to local storage and load from local

### ISSUE THREAD

**Issue by iooops** [tensorflow/tfjs-wechat#44]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Loading models from the internet can be slow sometimes.

> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.

It would be great if users can save tf models to local storage and local it from local next time when they open the app.

> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

/

> **Additional context**
> Add any other context or screenshots about the feature request here.

There's an attempt here: https://github.com/mogoweb/wechat-tfjs-examples

**Comment by pyu10055** [comment]
@iooops this is a good idea, I will explore the possibility of add wechat localStorage io handler.

**Comment by pyu10055** [comment]
I have added [save function](https://github.com/tensorflow/tfjs/pull/2676) to the GraphModel, will provide a localStorageIO handler for WeChat shortly. I noticed WeChat localStorage has a size limit of 10MB, which means model cannot exceed the size, you might want to quantize the model if the size exceeds.
