### ISSUE TITLE
cant find bodypix model on china mirror

### ISSUE THREAD

**Issue by jtrhb** [tensorflow/tfjs-wechat#49]
the response is 404 not found

**Comment by pyu10055** [comment]
@jtrhb what is the url you used for bodypix model? Thanks

**Comment by jtrhb** [comment]
https://www.gstaticcnapps.cn/tfjs-models/savedmodel/bodypix/mobilenet/float/050/model-stride16.json
That's what I used, which if you replace with storage.googleapis.com the request gets respond correctly.

**Comment by pyu10055** [comment]
@jtrhb we have resync the models, it should be working now. thank you for reporting.
