### ISSUE TITLE
tfjsPlugin 0.0.8 插件版本不存在

### ISSUE THREAD

**Issue by 2H0U** [tensorflow/tfjs-wechat#51]
打算使用0.0.8加入的localStorage支持，tfjs-core和tfjs-converter都已经改为1.5.2，但是开发工具报错：
> “provider:wx6afed118d9e81df9, version:0.0.8, 插件版本不存在,the version of the app/plugin is not
exist”。

在0.0.7及之前的版本里，plugin.localStorageIO是undefined。能否帮忙解决一下，感谢。

**Comment by pyu10055** [comment]
@2H0U 0.0.8 is published, was waiting for approval. thanks!

**Comment by 2H0U** [comment]
非常感谢，牛逼👍
