### ISSUE TITLE
localStorageIO缓存模型的问题

### ISSUE THREAD

**Issue by 2H0U** [tensorflow/tfjs-wechat#52]
我使用0.0.8版本的model.save(localStorageHandler)函数时会报错：

> Error info Error: APP-SERVICE-SDK:setStorageSync:fail exceed storage max size 10Mb

我用sizeof测量model的大小是1.4M，并且程序里没有其他地方使用过setStorageSync去占用缓存空间。请问可能是什么原因，谢谢。

**Comment by pyu10055** [comment]
@2H0U Is this an error reported by the IDE or the real device, can you check the storage usage in the IDE, see if there are multiple saved versions of the same model?

**Comment by 2H0U** [comment]
感谢回复，我检查过的，IDE的storage列表是空白的。我大概想了一下(也许不对)，微信小程序限制wx.setStorage每个key-value最多存1MB，所以可能需要把model结构拆解成多个不超过1MB的key-value。而model的数据结构里有circular structure，不能直接stringify，需要类似拓扑排序的过程进行拆解，所以结果可能会比原始内容大一些。我用的是lite mobilenetv2 ssd，量化到int16，权重文件大概8.5MB，包括4MB+4MB+0.5MB三个shard文件和一个json文件。文件使用loadGraphModel加载到内存，用一个叫object-sizeof的第三方插件测量内存的结果是1.4MB左右。

**Comment by pyu10055** [comment]
sounds like your models just slightly over the 10MB limit, it might be good to use the local file storage that is being added by [the PR](https://github.com/tensorflow/tfjs-wechat/pull/50).

**Comment by 2H0U** [comment]
多谢指点。我把fileStorageIO加到项目里，然后把loadGraphModel返回的模型传给fileStorageIO的save函数，但是console会报错

> TypeError: Converting circular structure to JSON

原因是file_storage这个文件里这句话失败了

> JSON.stringify(modelArtifactsWithoutWeights)

**Comment by 2H0U** [comment]
不好意思，这个fileStorageIO没有问题，是我之前使用方法错误，现在可以成功save和load模型。非常感谢！牛逼！

**Comment by pyu10055** [comment]
glad you made it work, thanks!
