### ISSUE TITLE
executeAsync内存泄漏

### ISSUE THREAD

**Issue by 2H0U** [tensorflow/tfjs-wechat#56]
我的调试方法如下：
1. 在Page的`onLoad`函数里调用`@tensorflow-models/coco-ssd/index.js`里的`ObjectDetection.prototype.load`加载模型，并在加载前使用`console.log(tf.memory())`记录内存占用。
2. 在`onUnload`函数里`dispose`模型，然后使用`console.log(tf.memory())`记录内存占用。
3. 除了模型加载和释放，所有其他操作都被注释掉。

我反复打开页面/关闭页面，得到结果如下：
1. onLoad
`{unreliable: false, numBytesInGPU: 0, numTensors: 0, numDataBuffers: 0, numBytes: 0}`
2. onUnload
`{unreliable: false, numBytesInGPU: 1080000, numTensors: 1, numDataBuffers: 1, numBytes: 1080000}`
3. onLoad
`{unreliable: false, numBytesInGPU: 0, numTensors: 1, numDataBuffers: 1, numBytes: 1080000}`
4. onUnload
`{unreliable: false, numBytesInGPU: 1080000, numTensors: 2, numDataBuffers: 2, numBytes: 2160000}`
5. onLoad
`{unreliable: false, numBytesInGPU: 0, numTensors: 2, numDataBuffers: 2, numBytes: 2160000}`
6. onUnload
`{unreliable: false, numBytesInGPU: 1080000, numTensors: 3, numDataBuffers: 3, numBytes: 3240000}`
7. onLoad
`{unreliable: false, numBytesInGPU: 0, numTensors: 3, numDataBuffers: 3, numBytes: 3240000}`
8. onUnload
`{unreliable: false, numBytesInGPU: 1080000, numTensors: 4, numDataBuffers: 4, numBytes: 4320000}`

可以看出每次释放模型后，总是多出1080000未释放的字节。我看到tfjs项目的issues里有人提到executeAsync导致内存泄漏。我测试了一下，感觉也是这里的问题。麻烦帮忙看一下。谢谢。

**Comment by pyu10055** [comment]
this bug is fixed, please upgrade to the latest tfjs-converter version (> 1.7.0)

**Comment by 2H0U** [comment]
感谢您的及时解答，我看到最新发布版本只到1.7.0，我再等一下吧。我目前的方法是，在页面unload时调用tf.engine().reset()。

**Comment by pyu10055** [comment]
@2H0U 1.7.0 should also work.

**Comment by 2H0U** [comment]
我测试了1.7.0，问题依然存在，页面关闭后tf.memory()总是报1080000未释放的字节，并且反复打开会累积。也许我的描述有误导性，这可能跟executeAsync是不同的问题。

**Comment by pyu10055** [comment]
@2H0U is your model loaded every time page is loaded? did you call model.dispose()? also did you dispose the tensor returned from the predict() method?

**Comment by pyu10055** [comment]
@2H0U any updates on this? thanks

**Comment by 2H0U** [comment]
抱歉这么久才回复，其实问题还是存在。只要打开页面，加载模型，然后关闭页面，内存占用就会增加。反复至少10次，程序就崩溃退出了。测试环节我只保留了模型加载的代码，预测的代码都注释掉了。

**Comment by pyu10055** [comment]
@2H0U just to confirm, did you call model.dispose() on page unload cycle?

**Comment by 2H0U** [comment]
是的，但是只调用model.dispose()是不够的，我还必须调用tf.engine().reset()。其实，从结果看，后者才是真正起作用的。如果只调用dispose，每次都有几百兆内存没有释放。我调试的环境是windows的微信开发工具。每次从模拟器开关页面，从资源管理器可以看到微信的内存占用都会增加。

**Comment by pyu10055** [comment]
@2H0U is it possible for you to share an example code to reproduce the problem? thanks

**Comment by 2H0U** [comment]
可以参考[这个项目](https://github.com/HunterXuan/wx-tfjs-demo)。我的项目就是基于这个修改的。在它的界面里选择 "基础篇->通用物体检测"。反复打开这个页面10次左右，真机就会崩溃。用模拟器的话，也可以看到明显的内存占用增长。

**Comment by pyu10055** [comment]
@2H0U you can use the coco-ssd version 2.0.3, which has the fix for the mem leak you found. Thank you for reporting the bug.

**Comment by guwei000** [comment]
1.7.2我也测试过，安卓上GPU内存一直无法被释放，IOS没有这个情况，而且安卓机上tf.engine().reset()会报错Right-hand side of 'instanceof' is not callable，我的解决办法是：将tf的库降到1.2.5就没事了，调用tf.dispose()后该释放的都会被释放
