### ISSUE TITLE
How to download model completely?

### ISSUE THREAD

**Issue by jingsong-liu** [tensorflow/tfjs-wechat#57]
Hello, I wanna download the model from mirror and load it locally. 
Here is what I have:

1. `
https://www.gstaticcnapps.cn/tfjs-models/savedmodel/posenet/mobilenet/float/050/model-stride16.json
`

2. `
https://www.gstaticcnapps.cn/tfjs-models/savedmodel/posenet/mobilenet/float/050/group1-shard1of1.bin
`

Then I put them in same folder of my local http server, when I load the model , it still reports error: 
`the lenght of Float32Array must be mutiple of 4`

So what should I do? do I missed some other files?

Thanks

**Comment by pyu10055** [comment]
@jingsong-liu This error usually means the weight file failed to be loaded. can you check the network tab of browser, what is url the model is loading the weight file from? or maybe share a screen capture here. thanks

**Comment by jingsong-liu** [comment]
![image](https://user-images.githubusercontent.com/10648096/77384848-65aa5980-6dc1-11ea-9267-cf8a52066ea5.png)
![image](https://user-images.githubusercontent.com/10648096/77385142-43650b80-6dc2-11ea-94c3-b5836012f755.png)
![image](https://user-images.githubusercontent.com/10648096/77385198-642d6100-6dc2-11ea-9b13-46f41328cee8.png)


```
Request URL: https://7072-prod-10ake-1301624657.tcb.qcloud.la/group1-shard1of1.bin?sign=ebba5cf4a27c9dcf0daaa563b5be16d2&t=1584756888
Request Method: GET
Status Code: 200 OK
Remote Address: 180.153.100.151:443
Referrer Policy: no-referrer-when-downgrade
```

The url `https://7072-prod-10ake-1301624657.tcb.qcloud.la` is tencent cloud storage where I upload the model

**Comment by pyu10055** [comment]
@jingsong-liu the size of the binary file seems to be wrong, it shows only 1918 bytes, can you make sure you have download the right .bin file.

**Comment by jingsong-liu** [comment]
Thank you so much, I downloaded the wrong .bin file. 
Problem solved now!
