### ISSUE TITLE
Why I test the mobilenet demo couldn't download model online

### ISSUE THREAD

**Issue by yikongge** [tensorflow/tfjs-wechat#60]
![图片](https://user-images.githubusercontent.com/35522808/78969246-15f5bd00-7b39-11ea-9185-4e30762218c0.png)
I could use the simulation
![图片](https://user-images.githubusercontent.com/35522808/78969378-6705b100-7b39-11ea-8344-be9af3d81436.png)
but when I use my phone ,it is pending

**Comment by yikongge** [comment]
在模拟器上可以用，真机调试时下载不了模型数据。

**Comment by pyu10055** [comment]
I depends on which URL you are downloading the model files from, you need to added to your project setting. 
![Screen Shot 2020-04-10 at 8 29 53 AM](https://user-images.githubusercontent.com/4018/79002548-8e428b00-7b05-11ea-9486-1e32d63e7228.png)
or enable debug model on the phone and disable domain check.
![Screen Shot 2020-04-10 at 8 31 18 AM](https://user-images.githubusercontent.com/4018/79002636-b9c57580-7b05-11ea-8570-acca14e628d6.png)

**Comment by yikongge** [comment]
@pyu10055 Thinks for your help. After I change configuration like yours,it running.
maybe because I used a old wechat version.
But when I use my model it can't running ,I think there are some wrong when I converter my keras model to a tfjs_graph_model.Of course that is another problem.Think you!!
