### ISSUE TITLE
Cannot load layers model completely in real machine debugging.

### ISSUE THREAD

**Issue by zhaocc1106** [tensorflow/tfjs-wechat#70]
tfjs-wechat plugin version:         tfjs-backend-cpu": "2.0.1",tfjs-backend-webgl": "2.0.1",tfjs-core": "2.0.1",tfjs-layers": "2.0.1"
WeChat version:                         IOS-7.0.13
WeChat base API version:          2.11.2
WeChat IDE version                   v1.02.1911180

The mini program can load layers model in pc-wechat-ide debugging but can't load completely in real machine debugging.
I found the group-shard bin downloading is pending as follows:
![image](https://user-images.githubusercontent.com/26559935/85491687-8b384080-b606-11ea-8487-b5c0094779e8.png)
And console log as follows:
![image](https://user-images.githubusercontent.com/26559935/85491987-0b5ea600-b607-11ea-93a6-d466c9d5893e.png)

I load layers model as follows:
```
flowerModel = await tfLayers.loadLayersModel('https://6169-ai-painter-7q1db-1302478925.tcb.qcloud.la/model.json?sign=5908e48b1382d81a4f8fbc164d423593&t=1592962790');
```

I don't known if it's bug of wechat. Can you help me? thanks very much!

**Comment by pyu10055** [comment]
If it is file loading issue, it could be related to your wechat domain whitelist. You can enable no domain check in project settings, and enable debugging on your real device.

**Comment by zhaocc1106** [comment]
> If it is file loading issue, it could be related to your wechat domain whitelist. You can enable no domain check in project settings, and enable debugging on your real device.

I had enabled no domain check, bug there is the same issue. I tried another model, one group bin is downloaded successfully.
![image](https://user-images.githubusercontent.com/26559935/85644640-1e867a00-b6ca-11ea-87bb-ead4fe5fe9c0.png)

**Comment by zhaocc1106** [comment]
It's a bug of wechat miniprogram ide.

**Comment by CoCa520** [comment]
same issue,has anyone resolved this issue yet?

**Comment by YifeiYang210** [comment]
same issue,has anyone resolved this issue yet?
