### ISSUE TITLE
如何调试tfjs-wechat代码

### ISSUE THREAD

**Issue by neiltian-tencent** [tensorflow/tfjs-wechat#76]
如何调试tfjs-wechat代码，导入tfjs-wechat代码，编译有错误。

**Comment by neiltian-tencent** [comment]
@pyu10055 demo/dist/app.json: demo/dist/app.json 未找到

**Comment by neiltian-tencent** [comment]
IDE: 微信开发者工具Stable 1.03.2006090

**Comment by pyu10055** [comment]
are you trying to run the demo code in this repo? You may need to follow the readme file on how to get the code compiled.

**Comment by neiltian-tencent** [comment]
I want to debug tfjs-backend-webgl in the WeChat applet, is there any recommendation?
